JohnSnowLabs/spark-nlp-workshop

- README.md
- strata/3-build-your-own-french-pos-tagger.ipynb
- strata/README.md
I'll be preparing notebooks inside `Strata` directory for users to follow the demo easily.
> Create Strata directory dedicated to the demo

- jupyter/training/english/dl-ner/ner.ipynb
Corrected path of the resource directory
> Updated ner.ipynb

- jupyter/training/english/dl-ner/ner_albert.ipynb
- jupyter/training/english/dl-ner/ner_xlnet.ipynb
added Albert and Xlnet example pipelines
> added Albert and Xlnet example pipelines

- tutorials/jupyter/5- How to use Spark NLP and Spark ML Pipelines.ipynb
> Fixed error outputs

- tutorials/Certification_Trainings/Healthcare/4.Clinical_DeIdentificiation.ipynb
Add more examples and include overwriter and WhiteList in NerConverter
> Update deidentification notebook

- tutorials/Certification_Trainings/Healthcare/4.Clinical_DeIdentificiation.ipynb
Added custom NER training and custom deidentifier to the Training Notebook
> add custom NER to the Deidentifier

- jupyter/annotation/english/document-normalizer/document_normalizer_notebook.ipynb
- jupyter/annotation/english/document-normalizer/html-docs/sample0.html
- jupyter/annotation/english/document-normalizer/html-docs/sample1.html
- jupyter/annotation/english/document-normalizer/html-docs/sample2.html
- jupyter/annotation/english/document-normalizer/json-docs/sample0.json
- jupyter/annotation/english/document-normalizer/xml-docs/C-CDAsample.xml
Added doc normalizer annotator notebook for Colab.
It includes usage examples for new incoming Spark NLP release 2.7.0 for DocumentNormalizer annotator.
> Added doc normalizer annotator notebook with usage examples

- tutorials/Certification_Trainings/Healthcare/10.Drug_Normalizer.ipynb
- tutorials/Certification_Trainings/Healthcare/23.Drug_Normalizer.ipynb
Add example in the healthcare certification training folder
> Added drug normalizer annotator notebook example

- tutorials/streamlit_notebooks/CONTEXTUAL_WORD_MEANING.ipynb
- tutorials/streamlit_notebooks/QUESTION_ANSWERING.ipynb
- tutorials/streamlit_notebooks/SENTENCE_GRAMMAR.ipynb
- tutorials/streamlit_notebooks/SENTENCE_RELATIONS.ipynb
- tutorials/streamlit_notebooks/TEXT_SUMMARIZATION.ipynb
I added notebooks for the following new demo apps:
- SENTENCE_GRAMMAR
- TEXT_SUMMARIZATION
- SENTENCE_RELATIONS
- CONTEXTUAL_WORD_MEANING
- QUESTION_ANSWERING
A few demo apps will have additional examples added, and I will update here when they have.
> Added 5 notebooks related to T5 tasks

- tutorials/streamlit_notebooks/healthcare/NER_DIAG_PROC_ES.ipynb
Added Spanish diagnoses and procedures notebook
> added Spanish diagnoses and procedures notebook

- jsl_sagemaker_setup_with_OCR.sh
install script for AWS sagemaker
> AWS sagemaker install script with OCR added

- jsl_colab_setup_with_OCR.sh
1 line to OCR+JSL+NLP install for colab
> 1 line to OCR+JSL+NLP install for colab

- jupyter/annotation/english/MultiDateMatcherMultiLanguage_en.ipynb
- jupyter/annotation/french/MultiDateMatcherMultiLanguage_fr.ipynb
- jupyter/annotation/german/MultiDateMatcherMultiLanguage_de.ipynb
- jupyter/annotation/italian/MultiDateMatcherMultiLanguage_it.ipynb
- jupyter/annotation/portuguese/MultiDateMatcherMultiLanguage_pt.ipynb
- jupyter/annotation/spanish/MultiDateMatcherMultiLanguage_es.ipynb
New notebooks for multilang multidate support for date matchers annotator.
> Added multilang multidate notebooks for en, fr, it, de, es, pt

- jupyter/annotation/english/graph-extraction/graph_extraction.ipynb
- jupyter/annotation/english/graph-extraction/graph_extraction_explode_entities.ipynb
- jupyter/annotation/english/graph-extraction/graph_extraction_intro.ipynb
Improving instructions on how to set parameters for extracting paths on graph extraction tutorial notebooks
> Improving instructions for graph extraction tutorial notebooks

- jupyter/training/english/dl-ner/mfa_ner_graphs_s3.ipynb
Adding notebook example to use MFA
> Adding notebook example to use MFA

- tutorials/logging/Comet_SparkNLP_Intergration.ipynb
This is a PR to include a notebook for the integration of Comet (PR https://github.com/JohnSnowLabs/spark-nlp/pull/6323)
Based on the example notebook provided by @DN6 <dhruv.nair@gmail.com>.
Both PRs should be merged about the same time, so the links in the documentation are working correctly.
> Added notebook for Comet examples

- tutorials/streamlit_notebooks/healthcare/NER_BERT_TOKEN_CLASSIFIER.ipynb
Added bert_token_classifier_ner_bionlp to the notebook.
> Updated NER_BERT_TOKEN_CLASSIFIER notebook.

- tutorials/logging/Comet_SparkNLP_Intergration.ipynb
Fixed some issues found by @DN6 in the notebook for Comet with additional improvements.
> Fixed issues with Comet notebook

- tutorials/Certification_Trainings/Healthcare/13.1.Finetuning_Sentence_Entity_Resolver_Model.ipynb
Fine-Tuning sentence ER notebook updated
> notebook updated

- tutorials/streamlit_notebooks/NER_FewNERD.ipynb
Added nerdl_fewnerd_100d to NER_FewNERD.ipynb.
> Updated NER_FewNERD.ipynb

- tutorials/streamlit_notebooks/SENTIMENT_EN_FINANCE.ipynb
Added SENTIMENT_EN_FINANCE notebook.
> Added SENTIMENT_EN_FINANCE notebook.

- platforms/sagemaker-studio/Dockerfile
- platforms/sagemaker-studio/README.md
- platforms/sagemaker-studio/SparkNLP_sagemaker.ipynb
- platforms/sagemaker-studio/app-image-config-input.json
- platforms/sagemaker-studio/ecr_configure.sh
- platforms/sagemaker-studio/environment.yml
- platforms/sagemaker-studio/license.json
installation instructions for sagemaker-studio. Dockerfile, envrionment.yml
> installation instructions

- platforms/sagemaker-studio/README.md
@egenc I'm improving the output info, also I'm parametrizing some of the strings. Can you take a look?
> Adds more output info and fixes

- tutorials/Certification_Trainings/Healthcare/utils/token_utils.py
> Script Uploaded: token_utils.py

- tutorials/streamlit_notebooks/CLASSIFICATION_UR_NEWS.ipynb
Added CLASSIFICATION_UR_NEWS.ipynb [#889](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/889)
> Added CLASSIFICATION_UR_NEWS.ipynb

- tutorials/streamlit_notebooks/CLASSIFICATION_QUESTIONPAIRS.ipynb
- tutorials/streamlit_notebooks/CLASSIFICATION_UR_NEWS.ipynb
- tutorials/streamlit_notebooks/Ner_masakhaner.ipynb
- tutorials/streamlit_notebooks/SENTIMENT_SW.ipynb
Added SENTIMENT_SW.ipynb [#891](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/891)
> Added SENTIMENT_SW.ipynb

- tutorials/streamlit_notebooks/CLASSIFICATION_RU_TOXIC.ipynb
Added CLASSIFICATION_RU_TOXIC.ipynb [#899](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/899)
> Added CLASSIFICATION_RU_TOXIC.ipynb

- jupyter/jsl_installation_script_ubuntu.sh
This commit will add -t parameter for fetching token from MYJSL to enable one-line command install from MYJSL
> FEATURE MYJSL-113: Install libraries on Ubuntu

- tutorials/Certification_Trainings/Healthcare/1.2.Contextual_Parser_Rule_Based_NER.ipynb
- changed pyspark to 3.1.2
- changes spark-nlp to public version
- removed all setup outputs
> updated session setup in contextual parser notebook

- patterns.json
patterns.json is added for Text Detection in an Image using Regex Patterns
> patterns.json is added

- tutorials/Certification_Trainings/Healthcare/1.2.Contextual_Parser_Rule_Based_NER.ipynb
added section 3.3 for regex matching multiple words
> added regex multi word section

- tutorials/streamlit_notebooks/BertForSequenceClassification.ipynb
create new notebook for B4SC
- 'bert_sequence_classifier_antisemitism'
- "bert_sequence_classifier_trec_coarse"
- "bert_sequence_classifier_age_news"
> BertForSequenceClassification

- tutorials/Certification_Trainings/Healthcare/11.Pretrained_Clinical_Pipelines.ipynb
- tutorials/Certification_Trainings/Healthcare/4.Clinical_DeIdentification.ipynb
The pretrained "clinical_deidentification" pipeline has been updated in both files.
> notebooks updated

- tutorials/streamlit_notebooks/BertForSequenceClassification.ipynb
Updated BertForSequenceClassification. 
Added new model for this notebook.
> updated notebook

- tutorials/streamlit_notebooks/BertForSequenceClassification.ipynb
bert_sequence_classifier_emotion model added in BertForSequenceClassification's notebook
> Updated notebook for BertForSequenceClassification

- tutorials/streamlit_notebooks/BertForSequenceClassification.ipynb
bert_sequence_classifier_banking77  was added to BertForSequenceClassification
> Modified BertForSequenceClassification notebook

- tutorials/streamlit_notebooks/Ner_masakhaner.ipynb
- Added _**"distilbert_base_token_classifier_masakhaner"**_ model to  **_Ner_masakhaner_** notebook.
> Updated for Ner_masakhaner Notebook

- jupyter/training/chinese/word-segmentation/WordSegmenter_train_chinese_segmentation.ipynb
Hi,
I added a new notebook for Chinese word segmentation. Contains example on how to train a WordSegmenterApproach.
> Added example notebook for training chinese word segmentation

- jupyter/annotation/english/sentence-detection/SentenceDetector_advanced_examples.ipynb
Related to https://github.com/JohnSnowLabs/spark-nlp/pull/7486
This PR adds a notebook on for extensive regex examples for the SentenceDetector. It includes a simple example and a reconstruction of the default regex.
> Notebook for advanced SentenceDetector Example

- tutorials/Certification_Trainings/Public/13.NLU_crashcourse_every_Spark_NLP_Model_in_one_line.ipynb
> updated nlu notebook

- tutorials/streamlit_notebooks/healthcare/NER_HUMAN_PHENOTYPE_GENE_CLINICAL.ipynb
Updated ner_human_phenotype_gene_clinical model demo streamlit notebook with new sample texts according to annotator feedbacks
> Updated notebook with new sample texts

- tutorials/streamlit_notebooks/public/QUESTION_ANSWERING_CLOSED_BOOK.ipynb
- tutorials/streamlit_notebooks/public/QUESTION_ANSWERING_OPEN_BOOK.ipynb
- public/QUESTION_ANSWERING_CLOSED_BOOK.ipynb
- public/QUESTION_ANSWERING_OPEN_BOOK.ipynb
> Updated demo colab notebook links

- tutorials/streamlit_notebooks/healthcare/CLASSIFICATION_RCT.ipynb
- tutorials/streamlit_notebooks/healthcare/NER_DIAG_PROC.ipynb
- _Created new colab notebook for CLASSIFICATION_RCT demo_
- _Updated colab notebook for NER_DIAG_PROC demo_
> Updated and created colab notebooks

- tutorials/Certification_Trainings/Healthcare/7.Clinical_NER_Chunk_Merger.ipynb
ChunkMerger NB is updated with TextMatcher and RegexMatcher annotators.
> NB-7 is updated with TextMatcher and RegexMatcher annotators

- jupyter/training/english/dl-ner/ner_graph_builder.ipynb
- jupyter/training/english/dl-ner/ner_logs.ipynb
Adding notebooks examples for building NER graph annotator and exporting NER logs
Please don't merge until spark-nlp 4.1.0 release
> Adding notebooks examples for NER training

- jupyter/training/english/classification/ClassifierDL_Train_and_Evaluate.ipynb
- jupyter/training/english/classification/MultiClassifierDL_Train_and_Evaluate.ipynb
- jupyter/training/english/classification/SentimentDL_Train_and_Evaluate.ipynb
Adding notebook example to configure cache_folder with an S3 URI
Please don't merge until spark-nlp 4.2.0 release
> Adding notebooks examples for setTestDataset parameter

- jupyter/prediction/english/Load_Model_From_S3.ipynb
Adding notebook example to configure cache_folder with an S3 URI
Please don't merge until spark-nlp 4.2.0 release
> Adding notebook example to configure cache_folder with an S3 URI

- tutorials/Certification_Trainings/Finance/13_Train_Financial_Classifiers.ipynb
- tutorials/Certification_Trainings/Legal/14_Train_Legal_Classifiers.ipynb
Adding new Fin+Leg classification training notebook.
> New FIN+LEG Classification training notebooks

- jupyter/annotation/multilingual/WordSegmenterMultilingual.ipynb
Adding notebook example to infer or train WordSegmenter annotator for multilingual texts
Please don't merge until spark-nlp 4.2.1 release
> Adding notebook for WordSegmenter Multilingual

- jupyter/annotation/english/coreference-resolution/Coreference_Resolution_SpanBertCorefModel.ipynb
This PR adds an example for the SpanBertCorefModel.
> Notebook for SpanBertCorefModel

- tutorials/Certification_Trainings/Healthcare/3.Clinical_Entity_Resolvers.ipynb
added new section about AssertionFilerer
> notebook update

- jupyter/prediction/english/Load_Model_from_GCP_Storage.ipynb
Adding notebook example for GCP Support in cache_folder
Please don't merge until spark-nlp 4.2.4 release
> Adding notebook example for GCP Support in cache_folder

- jupyter/training/english/entity-ruler/EntityRuler_LightPipeline.ipynb
Add missing spark-nlp pip installation in EntityRuler notebook
> Add missing spark-nlp pip installation in EntityRuler

- tutorials/Certification_Trainings_JSL/Legal/04.3.Training_Legal_Multilabel_Classifier.ipynb
- tutorials/Certification_Trainings_JSL/Legal/04.4.Training_Legal_Multilabel_Classifier.ipynb
- tutorials/Certification_Trainings_JSL/Legal/07.1.Training_Legal_Assertion.ipynb
- tutorials/Certification_Trainings_JSL/Legal/README.md
- tutorials/Certification_Trainings_JSL/README.md
Updated OOM legal notebooks.
07.1 was good to go
04.3 was split into 2-04.3,04.4
> Updated Legal Notebooks

- tutorials/Certification_Trainings/Healthcare/4.5.Clinical_Deidentification_Utility_Module.ipynb
new 4.5.Clinical_Deidentification_Utility_Module.ipynb notebook.
> deid module nb added

- tutorials/Certification_Trainings/Healthcare/README.md
I updated the Readme file. Made a mistake in writing the title before.
> Readme updated

- products/aws_azure/finance/13.Training_Finance_Assertion.ipynb
Fix Finance notebook on AWS Azure
> Fix aws azure finance notebooks

- tutorials/streamlit_notebooks/healthcare/CLINICAL_TEXT_SUMMARIZATION_ES.ipynb
Created new colab notebook for CLINICAL_TEXT_SUMMARIZATION_ES demo
> Created new notebook for spanish-clinical-summarization demo

- tutorials/Certification_Trainings/Healthcare/37.Text2SQL_Generation.ipynb
Added the new Text2SQL related notebook.
> Added new notebook

- tutorials/Annotation_Lab/Complete_ALab_Module_SparkNLP_JSL.ipynb
add doc_wise_annot param explation and usage to get_relation_extraction function
> add doc_wise_annot param to relation_extraction

- platforms/emr/emr_bootstrap_ocr_6_10_v4.sh
- Added OCR bootstrap.sh ( enables running healthcare and OCR libraries together)
> Add OCR bootstrap.sh

- tutorials/streamlit_notebooks/healthcare/NER_CLINICAL_MULTI.ipynb
> updated ner clinical multi streamlit notebook

- platforms/emr/Spark_OCR_EMR.ipynb
- Added HC 5th nb's equivalent EMR version 🕶️
> Added OCR EMR NB

- products/databricks/visual/README.md
- Changed the name of the file as visual , so updated the readme for the new link of Nbs
> Updated README.md

- generative-ai/Medical_Chatbot_RAG_JohnSnowLabs_Haystack.ipynb
- generative-ai/Medical_Chatbot_RAG_JohnSnowLabs_LangChain.ipynb
- generative-ai/README.md
> added new notebooks

- databricks/python/tutorials/healthcare_case_studies/Implementing_RAG_in_Healthcare_Workshop_in_Databricks_with_JohnSnowLabs.ipynb
> added new DBr notebook

- products/sagemaker/models/en.de_identify.clinical_pipeline/en.de_identify.clinical_pipeline.ipynb
- products/sagemaker/models/en.med_ner.bionlp.pipeline/en.med_ner.bionlp.pipeline.ipynb
- products/sagemaker/models/en.summarize.clinical_jsl_augmented.pipeline/en.summarize.clinical_jsl_augmented.pipeline.ipynb
Fixing S3 bucket path issues in AWS Marketplace notebooks.
- `en.de_identify.clinical_pipeline`
- `en.med_ner.bionlp.pipeline`
- `en.summarize.clinical_jsl_augmented.pipeline`
> Fix/AWS Marketplace Notebook S3 Bucket Path

- platforms/emr/NLP_EMR_Setup.ipynb
NLP_EMR_Setup notebook added (fix)
> NLP_EMR_Setup notebook added (fix)

- products/sagemaker/models/jsl-medical-summarization-qa-8b/jsl-medical-summarization-qa-8b.ipynb
This PR updates the marketplace artifacts with the latest files.
> MKT: Update Marketplace Artifacts

- Spark_NLP_Udemy_MOOC/Healthcare_NLP/Replacer.ipynb
> updated nb

- Spark_NLP_Udemy_MOOC/Healthcare_NLP/MedicalLLM.ipynb
MedicalLLM Mooc NB was added with some parameters.
> LLM Mooc NB was added

- tutorials/Certification_Trainings/Healthcare/4.8.Clinical_Deidentification_for_Structured_Data.ipynb
Created a 4.8.Clinical_Deidentification_for_Structured_Data notebook with two sections:
- Structured Deidentification for File-Based Data
- Structured Deidentification for Relational Database
> added clinical deidentification notebook for structured data including DB deid

- Spark_NLP_Udemy_MOOC/Healthcare_NLP/ContextualEntityFilterer.ipynb
- Spark_NLP_Udemy_MOOC/Healthcare_NLP/ContextualEntityRuler.ipynb
- healthcare-nlp/04.8.Clinical_Deidentification_for_Structured_Data.ipynb
- Added 04.8.Clinical_Deidentification_for_Structured_Data NB
- Updated 04.8.Clinical_Deidentification_for_Structured_Data NB
- Updated ContextualEntityFilterer Mooc NB
- Added ContextualEntityRuler Mooc NB
> Add & Update Notebooks

- healthcare-nlp/05.9.Spanish_Healthcare_Models.ipynb
- open-source-nlp/23.0.AutoGGUF_in_SparkNLP.ipynb
- tutorials/Certification_Trainings/Healthcare/48.Spanish_Healthcare_Models.ipynb
- Created _**23.0.AutoGGUF_in_SparkNLP.ipynb**_
-  Fixed Colab Links of NBs
> Create AutoGGUF Notebook

- tutorials/academic/Assertion_Detection_Text2Story2025/Combined_Assertion_Pipeline.ipynb
Combined Assertion Pipeline.
It is used in Beyond Negation Detection: Comprehensive Assertion Detection Models for Clinical Paper
> Combined Assertion Pipeline

- tutorials/Certification_Trainings/Healthcare/40.1.Text_Matcher_Internal.ipynb
text matcher internal notebook
> text matcher internal notebook

- Spark_NLP_Udemy_MOOC/Healthcare_NLP/PretrainedZeroShotNer.ipynb
- Added new MOOC notebook for PretrainedZeroShotNER annotator.
> New notebook PretrainedZeroShotNER

- Spark_NLP_Udemy_MOOC/Healthcare_NLP/StructuredJsonConverter.ipynb
- Added new MOOC notebook Structured json converter
> New notebook Structured json converter
